import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { plotAltFromMeta, plotCaptionFromMeta } from "../plotLabels";
import { extractPlotAttachments } from "./plotAttachments";
import { stripTurnActivityBlocks } from "../utils/messageStrip";
import type { ContentBlock, Message, PlotAttachment } from "../types";

interface TranscriptPrintViewProps {
  title: string;
  exportedAt: Date;
  messages: Message[];
}

function shouldInsertSpace(prev: string, next: string): boolean {
  const a = prev.trimEnd().at(-1);
  const b = next.trimStart().at(0);
  if (!a || !b) return false;
  if (/\s/.test(a) || /\s/.test(b)) return false;
  return /[\p{L}\p{N})\]]/u.test(a) && /[\p{L}\p{N}([{]/u.test(b);
}

function joinTextBlocks(parts: string[]): string {
  return parts.reduce((out, part) => {
    if (!out) return part;
    return `${out}${shouldInsertSpace(out, part) ? " " : ""}${part}`;
  }, "");
}

function messageText(content: string | ContentBlock[]): string {
  if (typeof content === "string") return content;
  return joinTextBlocks(content
    .filter((block) => block.type === "text" && block.text)
    .map((block) => block.text!));
}

function buildPlotsByIndex(messages: Message[]): Map<number, PlotAttachment[]> {
  const plotsByIndex = new Map<number, PlotAttachment[]>();
  let queued: PlotAttachment[] = [];
  messages.forEach((msg, i) => {
    const next = extractPlotAttachments(msg.content);
    if (next.length > 0) queued.push(...next);
    if (msg.role === "assistant" && queued.length > 0) {
      plotsByIndex.set(i, [...queued]);
      queued = [];
    }
  });
  return plotsByIndex;
}

function formatExportedAt(date: Date): string {
  return new Intl.DateTimeFormat(undefined, {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "numeric",
    minute: "2-digit",
  }).format(date);
}

function plotTypeLabel(type: string | undefined): string | null {
  if (!type) return null;
  return type
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function PrintPlot({ plot }: { plot: PlotAttachment }) {
  const caption = plotCaptionFromMeta(plot.src, plot.title);
  const alt = plotAltFromMeta(plot.src, "Analysis plot", plot.title);
  const typeLabel = plotTypeLabel(plot.plotType);
  const meta = [plot.groupLabel, typeLabel, plot.plotTimezone ? `Time axes: ${plot.plotTimezone}` : null]
    .filter(Boolean)
    .join(" · ");

  return (
    <figure className="print-plot" data-print-plot>
      <img src={plot.src} alt={alt} crossOrigin="anonymous" />
      {(caption || meta) && (
        <figcaption>
          {caption && <span className="print-plot-title">{caption}</span>}
          {meta && <span className="print-plot-meta">{meta}</span>}
        </figcaption>
      )}
    </figure>
  );
}

export default function TranscriptPrintView({
  title,
  exportedAt,
  messages,
}: TranscriptPrintViewProps) {
  const cleanMessages = stripTurnActivityBlocks(messages);
  const plotsByIndex = buildPlotsByIndex(cleanMessages);

  const sections = cleanMessages
    .map((msg, index) => {
      const text = messageText(msg.content).trim();
      const plots = plotsByIndex.get(index) ?? [];
      if (!text && plots.length === 0) return null;
      return { msg, index, text, plots };
    })
    .filter((x): x is NonNullable<typeof x> => Boolean(x));

  return (
    <article className="bb-print-root" data-print-host>
      <style>{PRINT_CSS}</style>
      <header className="bb-print-cover" data-print-cover>
        <p className="bb-print-kicker">bluebot Assistant Chat Export</p>
        <h1>{title.trim() || "Conversation"}</h1>
        <p className="bb-print-exported">Exported on {formatExportedAt(exportedAt)}</p>
        <p className="bb-print-muted">Generated by bluebot Assistant</p>
      </header>

      <div className="bb-print-messages">
        {sections.map(({ msg, index, text, plots }) => {
          const isUser = msg.role === "user";
          return (
            <section
              key={`${msg.role}-${index}`}
              className="bb-print-message"
              data-print-msg
            >
              <div className={isUser ? "bb-print-role user" : "bb-print-role assistant"}>
                {isUser ? "You" : "Assistant"}
              </div>
              <div className="bb-print-rule" />
              {text && (
                <div className="bb-print-markdown">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>{text}</ReactMarkdown>
                </div>
              )}
              {plots.length > 0 && (
                <div className="bb-print-plots">
                  {plots.map((plot, plotIndex) => (
                    <PrintPlot key={`${plot.src}-${plotIndex}`} plot={plot} />
                  ))}
                </div>
              )}
            </section>
          );
        })}
      </div>
    </article>
  );
}

const PRINT_CSS = `
.bb-print-root {
  background: #ffffff;
  box-sizing: border-box;
  color: #0f172a;
  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size: 14px;
  letter-spacing: normal;
  line-height: 1.68;
  text-rendering: optimizeLegibility;
  word-spacing: 0.03em;
  width: 100%;
}
.bb-print-cover {
  border-bottom: 1px solid #dbe5f3;
  margin-bottom: 22px;
  padding-bottom: 14px;
}
.bb-print-kicker {
  color: #3a5f9a;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.12em;
  margin: 0 0 6px;
  text-transform: uppercase;
}
.bb-print-cover h1 {
  color: #0f172a;
  font-size: 21px;
  font-weight: 700;
  letter-spacing: normal;
  line-height: 1.25;
  margin: 0 0 8px;
}
.bb-print-exported,
.bb-print-muted {
  color: #64748b;
  font-size: 12px;
  margin: 0;
}
.bb-print-muted {
  margin-top: 3px;
}
.bb-print-messages {
  display: block;
}
.bb-print-message {
  break-inside: avoid;
  margin: 0 0 28px;
  padding: 0;
}
.bb-print-role {
  font-size: 11px;
  font-weight: 800;
  letter-spacing: 0.08em;
  line-height: 1;
  margin-bottom: 7px;
  text-transform: uppercase;
}
.bb-print-role.user {
  color: #3a5f9a;
}
.bb-print-role.assistant {
  color: #334155;
}
.bb-print-rule {
  background: #e2e8f0;
  height: 1px;
  margin-bottom: 10px;
  width: 100%;
}
.bb-print-markdown > :first-child {
  margin-top: 0;
}
.bb-print-markdown > :last-child {
  margin-bottom: 0;
}
.bb-print-markdown {
  letter-spacing: normal;
  line-height: 1.68;
  text-rendering: optimizeLegibility;
  word-spacing: 0.03em;
}
.bb-print-markdown p {
  margin: 0 0 12px;
}
.bb-print-markdown p,
.bb-print-markdown li,
.bb-print-markdown td {
  overflow-wrap: break-word;
  white-space: normal;
  word-break: normal;
}
.bb-print-markdown h1,
.bb-print-markdown h2,
.bb-print-markdown h3,
.bb-print-markdown h4 {
  color: #0f172a;
  font-weight: 700;
  line-height: 1.25;
  margin: 18px 0 8px;
}
.bb-print-markdown h1 {
  font-size: 20px;
}
.bb-print-markdown h2 {
  font-size: 18px;
}
.bb-print-markdown h3 {
  font-size: 16px;
}
.bb-print-markdown h4 {
  font-size: 14px;
}
.bb-print-markdown ul,
.bb-print-markdown ol {
  margin: 0 0 12px 22px;
  padding: 0;
}
.bb-print-markdown li {
  margin: 4px 0;
}
.bb-print-markdown blockquote {
  border-left: 3px solid #cbd5e1;
  color: #475569;
  margin: 12px 0;
  padding: 2px 0 2px 12px;
}
.bb-print-markdown code {
  background: #f1f5f9;
  border: 1px solid #e2e8f0;
  border-radius: 4px;
  color: #1e293b;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace;
  font-size: 12px;
  padding: 1px 4px;
}
.bb-print-markdown pre {
  background: #f8fafc;
  border: 1px solid #dbe5f3;
  border-radius: 8px;
  color: #0f172a;
  margin: 12px 0;
  overflow: hidden;
  padding: 12px;
  white-space: pre-wrap;
  word-break: break-word;
}
.bb-print-markdown pre code {
  background: transparent;
  border: 0;
  border-radius: 0;
  display: block;
  font-size: 11px;
  padding: 0;
}
.bb-print-markdown table {
  border-collapse: collapse;
  font-size: 12px;
  margin: 12px 0;
  width: 100%;
}
.bb-print-markdown th,
.bb-print-markdown td {
  border: 1px solid #dbe5f3;
  padding: 6px 8px;
  text-align: left;
  vertical-align: top;
}
.bb-print-markdown th {
  background: #f8fafc;
  color: #334155;
  font-weight: 700;
}
.bb-print-markdown a {
  color: #2f65a7;
  text-decoration: underline;
}
.bb-print-plots {
  display: grid;
  gap: 14px;
  margin-top: 14px;
}
.print-plot {
  margin: 0;
  text-align: center;
}
.print-plot img {
  border: 1px solid #dbe5f3;
  border-radius: 8px;
  box-sizing: border-box;
  display: block;
  height: auto;
  margin: 0 auto;
  max-width: 100%;
}
.print-plot figcaption {
  color: #64748b;
  font-size: 11px;
  line-height: 1.35;
  margin-top: 6px;
}
.print-plot-title,
.print-plot-meta {
  display: block;
}
.print-plot-title {
  color: #475569;
  font-weight: 650;
}
`;
